/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-07-26 13:01:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Logica.ReservaControladora;
import Logica.HabitacionControladora;
import Logica.Habitacion;

public final class reservaCreate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1627301722520L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1627301801419L));
    _jspx_dependants.put("jar:file:/home/martin/NetBeansProjects/javaPoloTIC/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1627301722520L));
    _jspx_dependants.put("/cabecera.jsp", Long.valueOf(1627301722516L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Logica.HabitacionControladora");
    _jspx_imports_classes.add("Logica.Habitacion");
    _jspx_imports_classes.add("Logica.ReservaControladora");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Agregamos la siguiente libreria paa poder utilizar JSTL -->\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("        <title>Sistema de Reservas</title>\n");
      out.write("        <!-- jQuery -->\n");
      out.write("        <script src=\"lib/jquery/jquery.min.js\"></script>\n");
      out.write("        <!-- Font Awesome Icons -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css\">\n");
      out.write("        <!-- Theme style -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"lib/adminlte-3.0.4/css/adminlte.min.css\">\n");
      out.write("        <!-- Google Font: Source Sans Pro -->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\n");
      out.write("        <!-- jQuery -->\n");
      out.write("        <script src=\"lib/adminlte-3.0.4/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("        <!-- Bootstrap 4 -->\n");
      out.write("        <script src=\"lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Select 2 -->\n");
      out.write("        <link href=\"lib/select2-4.0.13/css/select2.min.css\" rel=\"stylesheet\"/>\n");
      out.write("        <link href=\"lib/select2-4.0.13/css/select2-bootstrap4.min.css\" rel=\"stylesheet\"/>\n");
      out.write("        <script src=\"lib/select2-4.0.13/js/select2.min.js\"></script>\n");
      out.write("        <script src=\"lib/select2-4.0.13/js/i18n/es.js\"></script>\n");
      out.write("        <!-- Jquery Confirm -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"lib/jquery-confirm-v3.3.4/jquery-confirm.min.css\">\n");
      out.write("        <script src=\"lib/jquery-confirm-v3.3.4/jquery-confirm.min.js\"></script>\n");
      out.write("        <!-- Bloque JAVASCRIPT -->\n");
      out.write("        <script>\n");
      out.write("            //agregar al campo numerico lo siguiente\n");
      out.write("            //onkeypress=\"return isNumberKey(event)\"\n");
      out.write("            function isNumberKey(evt)\n");
      out.write("            {\n");
      out.write("                var charCode = (evt.which) ? evt.which : evt.keyCode;\n");
      out.write("                if (charCode < 48 || charCode > 57)\n");
      out.write("                    return false;\n");
      out.write("                return true;\n");
      out.write("            }\n");
      out.write("            $(function () {\n");
      out.write("                $('.select2').select2({\n");
      out.write("                    theme: \"bootstrap4\",\n");
      out.write("                    language: 'es'\n");
      out.write("                });\n");
      out.write("                //Mostrar MODAL de Crear Huesped\n");
      out.write("                $('.btnAddHuesped').on('click', function () {\n");
      out.write("                    $('#myModalHuesped').modal('show');\n");
      out.write("                });\n");
      out.write("                //Ocultar y resetear modal al Crear Huesped\n");
      out.write("                $('#myModalHuesped').on('hidden.bs.modal', function (e) {\n");
      out.write("                    $('#frmHuesped').trigger('reset');\n");
      out.write("                });\n");
      out.write("                //Deshabilitamos el boton de Generar Reserva en cambio de fecha CheckIN\n");
      out.write("                $('#checkin').on('change', function (e) {\n");
      out.write("                    var btn = document.getElementById('btnGuardar');\n");
      out.write("                    btn.disabled = true;\n");
      out.write("                    var dateIN = $('input[name=\"checkin\"]').val();\n");
      out.write("                    var dateOUT = $('input[name=\"checkout\"]').val();\n");
      out.write("                    \n");
      out.write("                    if (dateIN >= dateOUT && dateOUT != \"\") {\n");
      out.write("                        $('input[name=\"checkin\"]').val(dateOUT);\n");
      out.write("                        $.alert({\n");
      out.write("                            title: 'Error!',\n");
      out.write("                            content: 'La fecha no debe ser mayor que la de CHECK-OUT',\n");
      out.write("                        });\n");
      out.write("                    } else if (dateOUT != \"\"){\n");
      out.write("                        //Calculamos la cantidad de dias para poder sacar el importe\n");
      out.write("                        date1 = new Date(dateIN);\n");
      out.write("                        date2 = new Date(dateOUT);\n");
      out.write("                        var cantDias = (date2 - date1) / (1000 * 60 * 60 * 24);\n");
      out.write("                        $('input[name=\"dias\"]').val(cantDias);\n");
      out.write("                        var precio = parseFloat(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${precio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\n");
      out.write("                        var importe = cantDias * precio;\n");
      out.write("                        console.log(importe);\n");
      out.write("                        if (importe != \"\"){\n");
      out.write("                            $('input[name=\"importe\"]').val(importe);\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("                //Chequeamos que la fecha de checkOUT sea mayor que checkIN\n");
      out.write("                $(\"#checkout\").on('change', function (e) {\n");
      out.write("                    var btn = document.getElementById('btnGuardar');\n");
      out.write("                    btn.disabled = true;\n");
      out.write("                    var dateIN = $('input[name=\"checkin\"]').val();\n");
      out.write("                    var dateOUT = $('input[name=\"checkout\"]').val();\n");
      out.write("                    if (dateIN >= dateOUT) {\n");
      out.write("                        $('input[name=\"checkout\"]').val(dateIN);\n");
      out.write("                        $.alert({\n");
      out.write("                            title: 'Error!',\n");
      out.write("                            content: 'La fecha debe ser mayor que la de CHECK-IN',\n");
      out.write("                        });\n");
      out.write("                    } else {\n");
      out.write("                        //Calculamos la cantidad de dias para poder sacar el importe\n");
      out.write("                        date1 = new Date(dateIN);\n");
      out.write("                        date2 = new Date(dateOUT);\n");
      out.write("                        var cantDias = (date2 - date1) / (1000 * 60 * 60 * 24);\n");
      out.write("                        $('input[name=\"dias\"]').val(cantDias);\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                //Funcion obtener capacidad habitacion\n");
      out.write("                //Cargamos en un input la capacidad de personas por habitacion seleccionada\n");
      out.write("                $(\"#habitacion\").on('change', function () {\n");
      out.write("                    //Inicializamos unas variables para la funcion\n");
      out.write("                    var btn = document.getElementById('btnGuardar');\n");
      out.write("                    btn.disabled = true;    //Desactivamos Boton por cada seleccion de Hab.\n");
      out.write("                    var ide = $(this).val();    //ID habitacion\n");
      out.write("                    //Variables de fechas de inicio y fin\n");
      out.write("                    var dateIN = $('input[name=\"checkin\"]').val();\n");
      out.write("                    var dateOUT = $('input[name=\"checkout\"]').val();\n");
      out.write("                    ///recorremos las habitaciones para sacar la capacidad\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                //Funcion para validar que este disponible la habitacion seleccionada\n");
      out.write("                $('#btnCheck').click(function () {\n");
      out.write("                    var btn = document.getElementById('btnGuardar');\n");
      out.write("                    var hab = $('#habitacion').val();\n");
      out.write("                    var checkIN = $('#checkin').val();\n");
      out.write("                    var checkOUT = $('#checkout').val();\n");
      out.write("                    var huesped = $('#huesped').val();\n");
      out.write("                    if (huesped == \"0\") {\n");
      out.write("                        $.alert({\n");
      out.write("                            title: 'Error!',\n");
      out.write("                            content: 'Debe seleccionar un Huésped',\n");
      out.write("                        });\n");
      out.write("                    } else {\n");
      out.write("                        $.ajax({\n");
      out.write("                            url: 'SvCheckHabitacion',\n");
      out.write("                            type: \"POST\",\n");
      out.write("                            data: {\n");
      out.write("                                'habitacion': hab,\n");
      out.write("                                'checkin': checkIN,\n");
      out.write("                                'checkout': checkOUT,\n");
      out.write("                            },\n");
      out.write("                            dataType: 'json',\n");
      out.write("                            success: function (data) {\n");
      out.write("                                if (data.isValidd) {\n");
      out.write("                                    $.alert({\n");
      out.write("                                        title: 'Error!',\n");
      out.write("                                        content: 'Habitación ocupada, por favor seleccione otra',\n");
      out.write("                                    });\n");
      out.write("                                    btn.disabled = true;\n");
      out.write("                                } else {\n");
      out.write("                                    $.alert({\n");
      out.write("                                        title: 'Confirmación!',\n");
      out.write("                                        content: 'Habitación disponible para la reserva',\n");
      out.write("                                    });\n");
      out.write("                                    btn.disabled = false;\n");
      out.write("                                }\n");
      out.write("\n");
      out.write("                            },\n");
      out.write("                            error: function (error) {\n");
      out.write("                                console.log('Error ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("                            }\n");
      out.write("                        });\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                //Chequeamos que la cantidad de personas no supere el limite de la Habitacion\n");
      out.write("                $(\"#cantidad\").on('change', function (e) {\n");
      out.write("                    var cantPersonas = $('input[name=\"cantidad\"]').val();\n");
      out.write("                    var cantHab = $('input[name=\"capHab\"]').val();\n");
      out.write("                    if (cantPersonas > cantHab) {\n");
      out.write("                        $.alert({\n");
      out.write("                            title: 'Error!',\n");
      out.write("                            content: 'La cantidad de personas supera el limite de la habitacion',\n");
      out.write("                        });\n");
      out.write("                        $('input[name=\"cantidad\"]').val(cantHab);\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    <body class=\"hold-transition layout-top-nav\">\n");
      out.write("\n");
      out.write("        <!-- Verificar si hay un usuario activo -->\n");
      out.write("        ");
 HttpSession misession = request.getSession();
            //Chequeo que exista un usuario
            String usuario = (String) request.getSession().getAttribute("username");
            if (usuario == null) {
                //Si no existe un usuario se redirecciona al LOGIN
                response.sendRedirect("loginSinLogin.jsp");
            } else {
                //Existe un usuario 
            }
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"wrapper\">\n");
      out.write("\n");
      out.write("            <!-- BARRA DE NAVEGACION -->\n");
      out.write("\n");
      out.write("            ");
      out.write("<!-- Navbar -->\n");
      out.write("<nav class=\"main-header navbar navbar-expand navbar-dark navbar-primary\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        \n");
      out.write("        <button class=\"navbar-toggler order-1\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\"\n");
      out.write("                aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <!-- MODULOS -->\n");
      out.write("        <div class=\"collapse navbar-collapse order-3\" id=\"navbarCollapse\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <!--Inicio-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"home.jsp\" class=\"nav-link\"><i class=\"fas fa-home\"></i>Inicio</a>\n");
      out.write("                </li>\n");
      out.write("                <!-- Reservas-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"SvReservaList\" class=\"nav-link\"><i class=\"far fa-calendar-alt\"></i>Reservas</a>\n");
      out.write("                </li>\n");
      out.write("                <!-- Huespedes-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"SvHuespedList\" class=\"nav-link\"><i class=\"fas fa-user-check\"></i>Huespedes</a>\n");
      out.write("                </li>\n");
      out.write("                <!--Habitaciones-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"SvHabitacionList\" class=\"nav-link\"><i class=\"fas fa-home\"></i>Habitaciones</a>\n");
      out.write("                </li>\n");
      out.write("                <!-- Tipos de Habitaciones-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"SvTipoList\" class=\"nav-link\"><i class=\"fas fa-hotel\"></i>Tipos</a>\n");
      out.write("                </li>\n");
      out.write("                <!-- Empleados-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"SvEmpleadoList\" class=\"nav-link\"><i class=\"fas fa-users\"></i>Empleados</a>\n");
      out.write("                </li>\n");
      out.write("                <!-- Usuarios-->\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a href=\"SvUsuarioList\" class=\"nav-link\"><i class=\"fas fa-users-cog\"></i>Usuarios</a>\n");
      out.write("                </li>\n");
      out.write("                <!-- Reportes-->\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a id=\"dropdownSubMenu1\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"\n");
      out.write("                       class=\"nav-link dropdown-toggle\"><i class=\"fas fa-file-alt\"></i>Reportes</a>\n");
      out.write("                    <ul aria-labelledby=\"dropdownSubMenu1\" class=\"dropdown-menu border-0 shadow\">\n");
      out.write("                        <li><a href=\"reporteDia.jsp\" class=\"dropdown-item\"><i\n");
      out.write("                                class=\"fas fa-calendar-day\"></i> Reservas por día</a></li>\n");
      out.write("                        <li><a href=\"reporteUsuario.jsp\" class=\"dropdown-item\"><i class=\"fas fa-address-card\"></i>\n");
      out.write("                            Reservas por Empleado</a></li>\n");
      out.write("                        <li><a href=\"reporteHuesped.jsp\" class=\"dropdown-item\"><i\n");
      out.write("                                class=\"fas fa-address-card\"></i> Reservas por Huésped</a></li>\n");
      out.write("                        <li><a href=\"reporteDiaGanancia.jsp\" class=\"dropdown-item\"><i class=\"fas fa-chart-bar\"></i>\n");
      out.write("                            Recaudación por día</a></li>\n");
      out.write("                        <li><a href=\"reporteMesGanancia.jsp\" class=\"dropdown-item\"><i\n");
      out.write("                                class=\"fas fa-chart-bar\"></i> Recaudación por rango de fechas</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Cerrar Sesion -->\n");
      out.write("        <ul class=\"order-1 order-md-3 navbar-nav navbar-no-expand ml-auto\">\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"index.jsp\" action=\"SvLogout\" method=\"POST\">\n");
      out.write("                    <i class=\"fas fa-power-off\" aria-hidden=\"true\"></i>Cerrar Sesión\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"content-wrapper\">\n");
      out.write("\n");
      out.write("                <!-- CABECERA -->\n");
      out.write("\n");
      out.write("                ");
      out.write("<div class=\"content-header\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row mb-2\">\n");
      out.write("            <div class=\"col-sm-6\">\n");
      out.write("                <h1 class=\"m-0 text-dark\"><strong>Sistema de Reservas</strong></h1>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6\">\n");
      out.write("                <ol class=\"breadcrumb float-sm-right\">\n");
      out.write("                    <h1 class=\"m-0 text-dark\"><small>Bienvenido  <strong>");
      out.print( request.getSession().getAttribute("username"));
      out.write("</strong></small></h1>\n");
      out.write("                </ol>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"content\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("\n");
      out.write("                        <!-- Bloque CONTENIDO -->\n");
      out.write("\n");
      out.write("                        <div class=\"container-fluid\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-12\">\n");
      out.write("                                    <div class=\"card bg-default\">\n");
      out.write("                                        <h5 class=\"card-header\">\n");
      out.write("                                            Generar Reserva\n");
      out.write("                                        </h5>\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            <!-- comment <form action=\"test.jsp\" method=\"POST\">-->\n");
      out.write("                                            <!-- Redireccionamos al Servlet correspondiente-->\n");
      out.write("                                            <form action=\"SvReservaCreate\" method=\"POST\">\n");
      out.write("                                                <div class=\"card-body\">\n");
      out.write("                                                    <label for=\"huesped\">\n");
      out.write("                                                        Seleccione el huesped\n");
      out.write("                                                    </label>\n");
      out.write("                                                    <div class=\"input-group\">\n");
      out.write("\n");
      out.write("                                                        <select class=\"form-control select2\" id=\"huesped\" name=\"huesped\" required>\n");
      out.write("                                                            <!-- Utilizamos JSTL para cargar el combobox-->\n");
      out.write("                                                            <option value=\"0\">---------</option>\n");
      out.write("                                                            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                                        </select>\n");
      out.write("\n");
      out.write("                                                        <div class=\"input-group-append\">\n");
      out.write("                                                            <button class=\"btn btn-success btn-flat btnAddHuesped\" type=\"button\">\n");
      out.write("                                                                <i class=\"fas fa-user-plus\"></i>\n");
      out.write("                                                            </button>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <div class=\"row\">\n");
      out.write("                                                        <div class=\"col-4\">\n");
      out.write("                                                            <label for=\"checkin\">\n");
      out.write("                                                                Check-IN\n");
      out.write("                                                            </label>\n");
      out.write("                                                            <div class=\"input-group\">\n");
      out.write("                                                                <div class=\"input-group-prepend datepicker\">\n");
      out.write("                                                                    <span class=\"input-group-text\"><i class=\"far fa-calendar-alt\"></i></span>\n");
      out.write("                                                                </div>\n");
      out.write("                                                                <input type=\"date\" class=\"form-control\" checkin id=\"checkin\" name=\"checkin\"\n");
      out.write("                                                                       placeholder=\"Ingrese la fecha\" required>\n");
      out.write("                                                            </div>\n");
      out.write("\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-4\">\n");
      out.write("                                                            <label for=\"checkout\">\n");
      out.write("                                                                Check-OUT\n");
      out.write("                                                            </label>\n");
      out.write("                                                            <div class=\"input-group\">\n");
      out.write("                                                                <div class=\"input-group-prepend datepicker\">\n");
      out.write("                                                                    <span class=\"input-group-text\"><i class=\"far fa-calendar-alt\"></i></span>\n");
      out.write("                                                                </div>\n");
      out.write("                                                                <input type=\"date\" class=\"form-control\" checkout id=\"checkout\" name=\"checkout\"\n");
      out.write("                                                                       placeholder=\"Ingrese la fecha de checkout\" required>\n");
      out.write("\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-4\">\n");
      out.write("                                                            <label for=\"dias\">\n");
      out.write("                                                                Cantidad de dias\n");
      out.write("\n");
      out.write("                                                            </label>\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"dias\" name=\"dias\"\n");
      out.write("                                                                   autocomplete=\"off\" readonly required>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <div class=\"row\">\n");
      out.write("                                                        <div class=\"col-4\">\n");
      out.write("                                                            <label for=\"habitacion\">\n");
      out.write("                                                                Habitación                                                    \n");
      out.write("                                                            </label>\n");
      out.write("                                                            <select class=\"form-control select2\" id=\"habitacion\" name=\"habitacion\">\n");
      out.write("                                                                <!-- Utilizamos JSTL para cargar el combobox-->\n");
      out.write("                                                                <option value=\"0\">---------</option>\n");
      out.write("                                                                ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                                                            </select>\n");
      out.write("                                                            <input type=\"hidden\" name=\"capHab\" value=\"0\">\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-4\">\n");
      out.write("                                                            <label for=\"cantidad\">\n");
      out.write("                                                                Cantidad de Personas\n");
      out.write("                                                            </label>\n");
      out.write("                                                            <input type=\"number\" min=\"1\" class=\"form-control\" id=\"cantidad\" name=\"cantidad\" \n");
      out.write("                                                                   value=\"1\" onkeypress=\"return isNumberKey(event)\" autocomplete=\"off\" required>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"col-4\">\n");
      out.write("                                                            <label for=\"importe\">\n");
      out.write("                                                                Importe\n");
      out.write("                                                            </label>\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"importe\" name=\"importe\"\n");
      out.write("                                                                   autocomplete=\"off\" readonly required>\n");
      out.write("                                                        </div>                                  \n");
      out.write("                                                    </div>\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <input type=\"hidden\" name=\"username\" value=\"");
      out.print( request.getSession().getAttribute("username"));
      out.write("\">\n");
      out.write("                                                    <br>\n");
      out.write("                                                    <!-- Boton para interactuar con ajax para validar la disponibilidad de la habitacion -->\n");
      out.write("                                                    <button type=\"button\" method=\"POST\" id=\"btnCheck\" name=\"accion\" value=\"chequear\" class=\"btn btn-success\">\n");
      out.write("                                                        <i class=\"far fa-calendar-check\"></i> Chequear habitacion\n");
      out.write("                                                    </button>\n");
      out.write("                                                    <button type=\"submit\" name=\"accion\" value=\"guardar\" id=\"btnGuardar\" disabled btnGuardar \n");
      out.write("                                                            class=\"btn btn-primary\" value=\"Generar reserva\">\n");
      out.write("                                                        <i class=\"fas fa-save\"></i> Generar Reserva\n");
      out.write("                                                    </button>\n");
      out.write("                                                    <a href=\"SvReservaList\" class=\"btn btn-danger\">\n");
      out.write("                                                        <i class=\"fas fa-times\"></i> Cancelar\n");
      out.write("                                                    </a>\n");
      out.write("\n");
      out.write("                                            </form>\n");
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        <!-- Modal -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        <div class=\"modal fade\" id=\"myModalHuesped\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                                             aria-hidden=\"true\">\n");
      out.write("                                            <form id=\"frmHuesped\" action=\"SvHuespedCreateReserva\" method=\"POST\">\n");
      out.write("                                                <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                                                    <div class=\"modal-content\">\n");
      out.write("                                                        <div class=\"modal-header\">\n");
      out.write("                                                            <h5 class=\"modal-title\" id=\"exampleModalLabel\">\n");
      out.write("                                                                <b><i class=\"fas fa-user-plus\"></i> Crear Huesped</b>\n");
      out.write("                                                            </h5>\n");
      out.write("                                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                                                                <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                                                            </button>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"modal-body\">\n");
      out.write("                                                            <div class=\"form-group\">\n");
      out.write("                                                                <label for=\"dni\">\n");
      out.write("                                                                    DNI\n");
      out.write("                                                                </label>\n");
      out.write("                                                                <input type=\"text\" class=\"form-control\" id=\"dni\" name=\"dni\"\n");
      out.write("                                                                       placeholder=\"Ingrese el DNI\" minlength=\"7\" autocomplete=\"off\" required>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"form-group\">\n");
      out.write("                                                                <label for=\"nombres\">\n");
      out.write("                                                                    Nombres\n");
      out.write("                                                                </label>\n");
      out.write("                                                                <input type=\"text\" class=\"form-control\" id=\"nombres\" name=\"nombres\"\n");
      out.write("                                                                       placeholder=\"Ingrese los nombres\" minlength=\"4\" autocomplete=\"off\" required>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"form-group\">\n");
      out.write("                                                                <label for=\"apellido\">\n");
      out.write("                                                                    Apellido\n");
      out.write("                                                                </label>\n");
      out.write("                                                                <input type=\"text\" class=\"form-control\" id=\"apellido\" name=\"apellido\"\n");
      out.write("                                                                       placeholder=\"Ingrese el apellido\" minlength=\"3\" autocomplete=\"off\" required>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"form-group\">\n");
      out.write("                                                                <label for=\"fechaNacimiento\">\n");
      out.write("                                                                    Fecha de Nacimiento\n");
      out.write("                                                                </label>\n");
      out.write("                                                                <div class=\"input-group\">\n");
      out.write("                                                                    <div class=\"input-group-prepend\">\n");
      out.write("                                                                        <span class=\"input-group-text\"><i class=\"far fa-calendar-alt\"></i></span>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                    <input type=\"date\" class=\"form-control\" id=\"fechaNacimiento\" name=\"fechaNacimiento\"\n");
      out.write("                                                                           placeholder=\"Ingrese la fecha de nacimiento\" required>\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"form-group\">\n");
      out.write("                                                                <label for=\"direccion\">\n");
      out.write("                                                                    Dirección\n");
      out.write("                                                                </label>\n");
      out.write("                                                                <input type=\"text\" class=\"form-control\" id=\"direccion\" name=\"direccion\"\n");
      out.write("                                                                       placeholder=\"Ingrese la dirección\" minlength=\"4\" autocomplete=\"off\" required>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            <div class=\"form-group\">\n");
      out.write("                                                                <label for=\"profesion\">\n");
      out.write("                                                                    Profesión\n");
      out.write("                                                                </label>\n");
      out.write("                                                                <input type=\"text\" class=\"form-control\" id=\"profesion\" name=\"profesion\"\n");
      out.write("                                                                       placeholder=\"Ingrese la profesión\" autocomplete=\"off\" required>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"modal-footer\">\n");
      out.write("                                                            <button type=\"submit\" class=\"btn btn-primary btn-block btn-flat\">\n");
      out.write("                                                                <i class=\"fas fa-save\"></i> Crear Huesped\n");
      out.write("                                                            </button>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </form>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- END Modal -->\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- FIN Bloque CONTENIDO -->\n");
      out.write("                </div>\n");
      out.write("                <!-- Footer -->\n");
      out.write("                ");
      out.write("<div class=\"card-footer\">\n");
      out.write("    <footer class=\"main-footer text-center\">\n");
      out.write("        <strong>Copyright &copy; 2021 <a href=\"home.jsp\">Sistema de Reservas</a>.</strong>\n");
      out.write("        <p>Desarrollado por: Lacheski, Martín Aníbal - Todos los derechos reservados.</p>\n");
      out.write("    </footer>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /reservaCreate.jsp(118,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/reservaCreate.jsp(118,12) '${habitaciones}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${habitaciones}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /reservaCreate.jsp(118,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("hab");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                    var h = parseInt(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hab.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\n");
            out.write("                    //verificamos que coincida la habitacion del listado\n");
            out.write("                    if (h == ide) {\n");
            out.write("                        //asignamos al input oculto la capacidad\n");
            out.write("                        $('input[name=\"capHab\"]').val(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hab.getCapacidad()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\n");
            out.write("                        //Calculamos el importe sacando precio * cantidad de dias\n");
            out.write("                        var precio = parseFloat(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hab.getPrecio()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\n");
            out.write("                        var dias = parseInt($('input[name=\"dias\"]').val());\n");
            out.write("                        var importe = dias * precio;\n");
            out.write("                        $('input[name=\"importe\"]').val(importe);\n");
            out.write("                    }\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /reservaCreate.jsp(246,60) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/reservaCreate.jsp(246,60) '${huespedes}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${huespedes}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /reservaCreate.jsp(246,60) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("huesp");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                                                <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${huesp.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${huesp.getApellido()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${huesp.getNombre()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("                                                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /reservaCreate.jsp(305,64) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/reservaCreate.jsp(305,64) '${habitaciones}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${habitaciones}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /reservaCreate.jsp(305,64) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("hab");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                                                                    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hab.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hab.getNombre()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("                                                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
